
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_display = QtWidgets.QLabel(self.centralwidget)
        self.label_display.setGeometry(QtCore.QRect(10, 80, 1111, 601))
        self.label_display.setText("")
        self.label_display.setPixmap(QtGui.QPixmap("image/t.png"))
        self.label_display.setScaledContents(True)
        self.label_display.setObjectName("label_display")
        self.line_1 = QtWidgets.QFrame(self.centralwidget)
        self.line_1.setGeometry(QtCore.QRect(0, 60, 1280, 20))
        self.line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_1.setObjectName("line_1")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 1280, 68))
        self.groupBox.setStyleSheet("background-color:rgb(220,220,220)")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_title = QtWidgets.QLabel(self.groupBox)
        self.label_title.setGeometry(QtCore.QRect(335, 19, 610, 35))
        self.label_title.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 18pt \"黑体\";")
        self.label_title.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_title.setObjectName("label_title")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 680, 1280, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(1120, 69, 20, 621))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 690, 1280, 180))
        self.groupBox_2.setStyleSheet("background-color: rgb(233, 239, 251);")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.tableWidget_detect = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget_detect.setGeometry(QtCore.QRect(190, 12, 1080, 151))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_detect.sizePolicy().hasHeightForWidth())
        self.tableWidget_detect.setSizePolicy(sizePolicy)
        self.tableWidget_detect.setMaximumSize(QtCore.QSize(16777215, 220))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_detect.setFont(font)
        self.tableWidget_detect.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidget_detect.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_detect.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_detect.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget_detect.setAlternatingRowColors(True)
        self.tableWidget_detect.setWordWrap(False)
        self.tableWidget_detect.setRowCount(4)
        self.tableWidget_detect.setObjectName("tableWidget_detect")
        self.tableWidget_detect.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_detect.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_detect.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_detect.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget_detect.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_detect.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_detect.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_detect.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_detect.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_detect.setItem(2, 0, item)
        self.tableWidget_detect.horizontalHeader().setVisible(False)
        self.tableWidget_detect.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_detect.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_detect.verticalHeader().setVisible(False)
        self.tableWidget_detect.verticalHeader().setCascadingSectionResizes(False)
        self.line_7 = QtWidgets.QFrame(self.groupBox_2)
        self.line_7.setGeometry(QtCore.QRect(170, 0, 20, 171))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 12, 161, 151))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("image/img.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(1130, 215, 151, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(1130, 525, 151, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.cancel = QtWidgets.QPushButton(self.centralwidget)
        self.cancel.setGeometry(QtCore.QRect(1140, 584, 130, 60))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cancel.setFont(font)
        self.cancel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cancel.setObjectName("cancel")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(1140, 427, 130, 60))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.start.setFont(font)
        self.start.setFocusPolicy(QtCore.Qt.NoFocus)
        self.start.setObjectName("start")
        self.toolButton_camera = QtWidgets.QPushButton(self.centralwidget)
        self.toolButton_camera.setGeometry(QtCore.QRect(1140, 273, 130, 60))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.toolButton_camera.setFont(font)
        self.toolButton_camera.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolButton_camera.setObjectName("toolButton_camera")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(1130, 370, 151, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.toolButton_video = QtWidgets.QPushButton(self.centralwidget)
        self.toolButton_video.setGeometry(QtCore.QRect(1140, 115, 130, 60))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.toolButton_video.setFont(font)
        self.toolButton_video.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolButton_video.setObjectName("toolButton_video")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "跌倒检测系统"))
        self.label_title.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt;\">思绪无限</span></p><p><span style=\" font-size:8pt; font-style:italic;\">sixuwuxian@aliyun.com</span></p><p><span style=\" font-size:8pt; font-style:italic;\">version: v1.0</span></p></body></html>"))
        self.label_title.setText(_translate("MainWindow", "跌倒检测系统"))
        item = self.tableWidget_detect.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget_detect.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_detect.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_detect.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "序号"))
        item = self.tableWidget_detect.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "画面标识"))
        item = self.tableWidget_detect.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "时间"))
        __sortingEnabled = self.tableWidget_detect.isSortingEnabled()
        self.tableWidget_detect.setSortingEnabled(False)
        self.tableWidget_detect.setSortingEnabled(__sortingEnabled)
        self.cancel.setText(_translate("MainWindow", "取消运行"))
        self.start.setText(_translate("MainWindow", "开始运行"))
        self.toolButton_camera.setText(_translate("MainWindow", "本地摄像头"))
        self.toolButton_video.setText(_translate("MainWindow", "本地上传"))
import img_rc
